version: '3.8'

services:
  db:
    image: postgres:17.4-alpine
    container_name: car_showcase_java_database
    restart: always
    ports:
      - 5433:5432
    volumes:
      - car_showcase_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: car_showcase_dev

volumes:
  car_showcase_data:
